export {localStorageBox} from "src/local_storage_box"
export {whileMounted, onMount} from "src/functions/base_tag"
export {tag} from "src/functions/html_tag"
export type {HTMLTagDescription} from "src/functions/html_tag"
export {svgTag} from "src/functions/svg_tag"
export type {SVGTagDescription} from "src/functions/svg_tag"
export {waitDocumentLoaded} from "src/wait_document_loaded"
export {defineControl} from "src/control"
